global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus 자체 모니터링
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # 아바타 애플리케이션 모니터링
  - job_name: 'avatar-app'
    static_configs:
      - targets: ['avatar-app:5000']
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s

  # Nginx 모니터링 (nginx-prometheus-exporter 필요)
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:9113']
    scrape_interval: 30s

  # Redis 모니터링 (redis_exporter 필요)
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 30s

  # Node Exporter (시스템 메트릭)
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s

  # Docker 컨테이너 모니터링 (cAdvisor)
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 30s

# 알림 규칙 (선택적)
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# 원격 쓰기 설정 (선택적)
# remote_write:
#   - url: "https://your-remote-prometheus.com/api/v1/write"

# 원격 읽기 설정 (선택적)  
# remote_read:
#   - url: "https://your-remote-prometheus.com/api/v1/read"
